### ISSUE TITLE
Audio does not work on iphone

### ISSUE THREAD

**Issue by ghost** [iot-fever/IoTFeverGame#13]
Implement Kenny's Audio branch into the Master branch

**Comment by aedelmann** [comment]
Is this any different from issue #8 ?

**Comment by zubairhamed** [comment]
Implementation in e0dba1f3404af777b1bbb6415d0648c5dbf3947a.

Not sure if it overlaps this issue

**Comment by shevken** [comment]
Same except mine is in a separate class "AudioService".

**Comment by zubairhamed** [comment]
Maybe the AudioService can be exposed to the VisualizerView to get the audio metadata for the Visualizer.
