### ISSUE TITLE
Enable game settings

### ISSUE THREAD

**Issue by shevken** [iot-fever/IoTFeverGame#17]
Allow external configuration of game settings like:
- UUID of sensors
- IP address of the player name/score REST services
  ...

**Comment by zubairhamed** [comment]
more possible configuration to be externalized:
- music to be used for the game itself
- game length 
- number of lives (defaults to 3 or 5)
- enable/disable REST Service connectivity (in case if REST Service is for whatever reason unavailable, game can still be played w/o a player defined)?
